version: '3.8'

services:
  admin-backend:
    build:
      context: ./tesis-backend
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development

  shooter-backend:
    build:
      context: ./tesis-facial-recognition
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  admin-frontend:
    build:
      context: ./tesis-frontend-admin
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true

  shooter-frontend:
    build:
      context: ./tesis-frontend-shooter
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
